version: "3"

services:
  postgres:
    image: "postgres:12.0"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=urlDB
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data